name: Test Jira Serial Execution

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
    
    - name: Create .env file with Jira enabled
      run: |
        cat > .env << EOF
        # Base settings
        BASE_URL=https://google.com
        BROWSER=chromium
        HEADLESS=true
        SLOW_MO=0
        DEFAULT_TIMEOUT=30000
        
        # Jira settings - ENABLED
        JIRA_ENABLED=true
        JIRA_BASE_URL=${{ secrets.JIRA_BASE_URL }}
        JIRA_USERNAME=${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY=${{ secrets.JIRA_PROJECT_KEY }}
        JIRA_ISSUE_TYPE=Bug
        JIRA_CREATE_DUPLICATES=false
        
        # Disable AI
        AI_FEATURES_ENABLED=false
        AI_DATA_GENERATION_ENABLED=false
        AI_TEST_ANALYSIS_ENABLED=false
        AI_TEST_GENERATION_ENABLED=false
        
        # Database placeholders
        POSTGRES_HOST=localhost
        POSTGRES_PORT=5432
        POSTGRES_DB=testdb
        POSTGRES_USER=postgres
        POSTGRES_PASSWORD=postgres
        
        CLICKHOUSE_HOST=localhost
        CLICKHOUSE_PORT=8123
        CLICKHOUSE_DB=default
        CLICKHOUSE_USER=default
        CLICKHOUSE_PASSWORD=
        
        # AWS placeholders
        AWS_REGION=us-east-1
        AWS_ACCESS_KEY_ID=
        AWS_SECRET_ACCESS_KEY=
        EOF
        
        echo "✅ Created .env file"
    
    - name: Verify Jira is enabled
      run: python test_ci_jira_simple.py
    
    - name: Run SINGLE test WITHOUT parallel execution
      run: |
        echo "=== Running single test without xdist ==="
        python -m pytest tests/test_jira_simple.py::test_simple_fail -v -s --no-cov -p no:xdist
        
    - name: Check if Jira ticket was created
      run: |
        echo "Check the output above for 'Created Jira issue:' message"